{ lib, config, ... }:
let
  cfg = config.partitions;
  storePrefix = "${cfg.store.label-prefix}";
  storeVerityPrefix = "${cfg.store-verity.label-prefix}";
  # compressed partitions generated by repart have the format
  # baseName = repart.name + repart.version
  sourcePrefix = config.image.repart.name;
in
{
  config.systemd.sysupdate = lib.mkIf cfg.enable {
    enable = true;

    transfers = {
      "10-store" = {
        Source = {
          MatchPattern = [ "${sourcePrefix}_@v.store.raw.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "partition";
          Path = "auto"; # TODO breaks?
          # Path = "/usr/nix/store";
          MatchPattern = [ "${storePrefix}_@v" ];
          # MatchPartitionType = "";
          InstancesMax = 2;
          ReadOnly = "yes";
        };
        Transfer = {
          ProtectVersion = "%A";
        };
      };

      "20-store-verity" = {
        Source = {
          MatchPattern = [ "${sourcePrefix}_@v.store-verity.raw.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "partition";
          Path = "auto";
          MatchPattern = [ "${storeVerityPrefix}_@v" ];
          InstancesMax = 2;
          ReadOnly = "yes";
        };
      };

      "30-uki" = {
        Source = {
          MatchPattern = [ "${config.boot.uki.name}_@v.efi.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "regular-file";
          Path = "/EFI/Linux";
          PathRelativeTo = "boot";
          MatchPattern = [ "${config.boot.uki.name}_@v.efi" ];
          Mode = "0444";
          InstancesMax = 2;
        };
      };
    };
  };
}
