{ lib, config, ... }:
let
  cfg = config.partitions;
  storePrefix = "${cfg.store.label-prefix}";
  storeVerityPrefix = "${cfg.store-verity.label-prefix}";
  # compressed partitions generated by repart have the format
  # baseName = repart.name + repart.version
  sourcePrefix = config.image.repart.name;
in
{
  config.systemd.sysupdate = lib.mkIf cfg.enable {
    enable = true;

    transfers = {
      "10-store" = {
        Source = {
          MatchPattern = [ "${sourcePrefix}_@v.store.raw.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "partition";
          Path = "auto";
          MatchPattern = [ "${storePrefix}_@v" ];
          InstancesMax = 2;
          ReadOnly = "yes";
        };
        Transfer = {
          ProtectVersion = "%A";
        };
      };

      "20-store-verity" = {
        Source = {
          MatchPattern = [ "${sourcePrefix}_@v.store-verity.raw.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "partition";
          Path = "auto";
          MatchPattern = [ "${storeVerityPrefix}_@v" ];
          InstancesMax = 2;
          ReadOnly = "yes";
        };
      };

      "30-uki" = {
        Source = {
          # The UKI filename embeds the systemd-boot try counter as a
          # `+<tries>` suffix (e.g. `name_2+2.efi`), so the transfer's
          # match pattern must include the `@t` (tries) placeholder after
          # the `@v` (version) one. Without this the payload UKI would
          # never match and the A/B update would silently fail.
          MatchPattern = [ "${config.boot.uki.name}_@v+@t.efi.zst" ];
          Path = "/var/updates/";
          Type = "regular-file";
        };
        Target = {
          Type = "regular-file";
          Path = "/EFI/Linux";
          PathRelativeTo = "boot";
          MatchPattern = [ "${config.boot.uki.name}_@v+@t.efi" ];
          Mode = "0444";
          InstancesMax = 2;
        };
      };
    };
  };
}